export const supplierExportSettings = {
  offset: 0,
  limit: 25,
  search: "",
  order: "desc",
  sort: "created_at",
  // "dropdown":"supplier",
  type: "",
  status: "",
  filter: {
    // "startDate": "2024-05-01",
    // "endDate": "2024-05-17",
    dateField: "created_at",
  },
  selected_ids: [
    // "053019db-4f20-4df4-89ba-107856a13fce",
    // "19ab8bc5-6703-403b-a0bc-5ed042b2d35a",
    // "19c6d0d8-d6e0-49cc-b3ff-ad336424e5cf",
    // 375,371,370
  ],
  table_name: "supplier_details",
  fields: {
    supplier_name: "Supplier Name",
    emailID: "Email ID",
    emailRefKey: "Email reference key",
    updateByAdmin: "Updated by admin",
    mobile: "Mobile",
    telephone: "Telephone",
    designation: "Designation",
    contactPersonName: "Contact Person Name",
    cinNo: "CIN No",
    aadharNo: "Aadhar No",
    officeDetails: "Office Details",
    paymentMethod: "Payment Method",
    website: "Website",
    phoneNo: "Phone No",
    pin: "PIN",
    city: "City",
    country: "Country",
    address3: "Address 3",
    address2: "Address 2",
    address1: "Address 1",
    streetNo: "Street No",
    source: "Source",
    add: "ADD",
    state: "State",
    department_id: "Department ID",
    department: "Department",
    sap_code: "SAP Code",
    sap_status: "SAP Status",
    sap_code_time: "SAP Code Time",
    status: "Status",
    level1status: "Level 1 Status",
    level2status: "Level 2 Status",
    status_update_date: "Status Update Date",
    comment: "Comment",
    gstNo: "GST No",
    panNo: "PAN No",
    subscriber_id: "Subscriber ID",
    type: "Type",
    tds_type: "TDS Type",
    tds_code: "TDS Code",
    tds_subject: "TDS Subject",
    tds_receipent: "TDS Receipent",
    currency: "Currency",
    turnover: "Turnover",
    turnover2: "Turnover 2",
    turnover3: "Turnover 3",
    first: "First",
    second: "Second",
    third: "Third",
    p_bank_account_number: "P Bank Account Number",
    msme_no: "MSME No",
    companyFoundYear: "Company Found Year",
    promoterName: "Promoter Name",
    companyType: "Company Type",
    nameOfBusiness: "Name Of Business",
    businessType: "Business Type",
    msmeType: "MSME Type",
    addressOfPlant: "Address Of Plant",
    nameOfOtherGroupCompanies: "Name Of Other Group Companies",
    listOfMajorCustomers: "List Of Major Customers",
    detailsOfMajorLastYear: "Details Of Major Last Year",
    msmeImage: "MSME Image",
    gstImage: "GST Image",
    cancelledChequeImage: "Cancelled Cheque Image",
    panCardImage: "PAN Card Image",
    pfAttachment: "PF Attachment",
    otherAttachments: "Other Attachments",
  },
};

export const asnExportSettings = {
  offset: 0,
  limit: 25,
  search: "",
  order: "desc",
  sort: "createdAt",
  // "dropdown":"supplier",
  type: "",
  status: "",
  filter: {
    // "startDate": "2024-05-01",
    // "endDate": "2024-05-17",
    dateField: "created_at",
  },
  //   selected_ids: [
  //     // "053019db-4f20-4df4-89ba-107856a13fce",
  //     // "19ab8bc5-6703-403b-a0bc-5ed042b2d35a",
  //     // "19c6d0d8-d6e0-49cc-b3ff-ad336424e5cf",
  //     // 375,371,370
  //   ],
  table_name: "asns",
  fields: {
    // "id":"ID",
    departmentId: "Department ID",
    poNo: "PO Number",
    poDate: "PO Date",
    asnNo: "ASN Number",
    plantId: "Plant ID",
    supplierId: "Supplier ID",
    dispatchDate: "Dispatch Date",
    type: "Type",
    carrier: "Carrier",
    lineItems: "Line Items",
    status: "Status",
    gst: "GST",
    pan: "PAN",
    gstInvoiceNumber: "GST Invoice Number",
    shipToAddress: "Ship To Address",
    billToAddress: "Bill To Address",
    remarks: "Remarks",
    file: "File",
    eWayBillNo: "e-Way Bill Number",
    irnNo: "IRN Number",
    qrcode: "QR Code",
    invoiceType: "Invoice Type",
    baseLineDate: "Base Line Date",
    grnId: "GRN ID",
    sesId: "SES ID",
    giId: "GI ID",
    storageLocation: "Storage Location",
    companyPAN: "Company PAN",
    companyGST: "Company GST",
    createdAt: "Created At",
    updatedAt: "Updated At",
    requested: "Requested",
    requestedStatus: "Requested Status",
    requestedTime: "Requested Time",
    requestedRemarks: "Requested Remarks",
    accepted: "Accepted",
    acceptedStatus: "Accepted Status",
    acceptedTime: "Accepted Time",
    acceptedRemarks: "Accepted Remarks",
    Invoiced: "Invoiced",
    InvoicedStatus: "Invoiced Status",
    InvoicedTime: "Invoiced Time",
    invoicedRemarks: "Invoiced Remarks",
    Cancel: "Cancel",
    CancelStatus: "Cancel Status",
    CancelTime: "Cancel Time",
    CancelRemarks: "Cancel Remarks",
    MaterialShipped: "Material Shipped",
    MaterialShippedTime: "Material Shipped Time",
    MaterialShippedStatus: "Material Shipped Status",
    MaterialShippedRemarks: "Material Shipped Remarks",
    MaterialGateInward: "Material Gate Inward",
    MGITime: "MGI Time",
    MaterialGateInwardStatus: "Material Gate Inward Status",
    MaterialGateInwardRemarks: "Material Gate Inward Remarks",
    MaterialReceived: "Material Received",
    MaterialReceivedTime: "Material Received Time",
    MaterialReceivedStatus: "Material Received Status",
    MaterialReceivedRemarks: "Material Received Remarks",
    QualityApproved: "Quality Approved",
    QualityApprovedTime: "Quality Approved Time",
    QualityApprovedStatus: "Quality Approved Status",
    QualityApprovedRemarks: "Quality Approved Remarks",
    header: "Header",
    item: "Item",
    sesCode: "SES Code",
    serviceActivity: "Service Activity",
    sesStatus: "SES Status",
    sesTime: "SES Time",
    vendor: "Vendor",
    Item: "Item",
    giCode: "GI Code",
    giStatus: "GI Status",
    giTime: "GI Time",
  },
};
